databases:
  - name: resumefit-db
    plan: free
    databaseName: resumefit
    user: resumefit

services:
  - type: web
    name: resumefit
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn resumefit.wsgi --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resumefit-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
